version: '3.8'
services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data && node ./db-migrate.js"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8002:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
