name: 'Terraform'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: package lambda
        run: |
          mkdir nodejs
          cp package.json ./nodejs
          cp package-lock.json ./nodejs
          npm install --omit=dev --prefix ./nodejs
          zip -r ./.github/workflows/layer.zip nodejs/
          zip -r ./.github/workflows/lambda.zip src/ package.json 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./.github/workflows/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./.github/workflows/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}